### ISSUE TITLE
Repository: make a connection to server to ensure the port is actually open

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3D#126]
Might have to make the client respond with something. ping/pong

**Comment by cwbooth5** [comment]
My suggestion is we initiate a (TCP or UDP?) connection from the server repo that attempts to send a string of text in a payload. The client reverses the string and echoes it back.

We add the server into our list after it proves reverse/ingress connectivity with this check.

Did you want to hold the server out of the list of active servers until it passes this check?

**Comment by cwbooth5** [comment]
I can look for an open port, but making the client do that little work to reverse the string effectively proves it's someone else in our little fugitive ecosystem. They play by our rules.

**Comment by cwbooth5** [comment]
One thing to consider is if we are using UDP here, dropped packets could bite us. In the case of UDP we might want to send three packets/responses and pass if we see just one of them.
