### ISSUE TITLE
Pick a different port. Also have port read from config file.

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3D#24]

**Comment by cwbooth5** [comment]
Which port are you talking about? The TCP and UDP 3000? Why do you need to change it?

**Comment by Wavesonics** [comment]
Ya probably don't need to pick a new one, I guess 3000 is fine?

Though we will need a way to pass an argument to the exe to define the port, that way we can run multiple servers on the same machine.

**Comment by cwbooth5** [comment]
I see. I suggest picking another higher ephemeral set of ports. We have up to 65534, so maybe pick a range of len(whatever) starting at 31000? (for example)

**Comment by Wavesonics** [comment]
This work is done now.
Default port is now `31000`
Servers can specify a port via command line: `--port 31001`
And clients can specify a port when connecting to a server.

**Comment by Wavesonics** [comment]
example:
`./Godot_v3.2.1-stable_linux_server.64 --main-pack data.pck --port 31001`
