### ISSUE TITLE
Maker docker server process repeatable

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3D#32]
Document the process in the readme, and create any sort of scripts or docker files necessary to setup a dedicated server on DO

**Comment by cwbooth5** [comment]
ON IT

**Comment by cwbooth5** [comment]
OK tell me if you can follow that build process to get the container running locally.

**Comment by Wavesonics** [comment]
Whoa this is great, awesome work @cwbooth5 !

Seeing how much is there, lets move the docker part `Building and Deploying the Server Container` and down, to it's own markdown file.

Maybe called: `server_deployment.md` or something, right in the root directory.

**Comment by cwbooth5** [comment]
OK changed.
