### ISSUE TITLE
Test different Dropplets on Digital Ocean

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3D#44]
The "Starter" droplets are WAY cheaper, starting at $5/month (for 1 CPU, no hyper threading)

lets figure out how cheap we can how and have it still run!

"Standard" 1GB RAM / 3 CPU for $15 might work for us?

Lets try them out. I can print to the terminal the current FPS of the engine to give us cheap & fast performance monitor.

**Comment by Wavesonics** [comment]
These are not "Docker" droplets, so we'll have to install Docker on a standard distro (use Alpine Linux or what ever you want).

**Comment by cwbooth5** [comment]
I'll go alpine in the container itself. For the VM OS, I'll see what they offer and what is lightweight.

**Comment by Wavesonics** [comment]
Looks like 3cpu / 1gb droplet can probably host 2 game servers, lets use that going forward
