### ISSUE TITLE
Install GIT LFS in main Fugitive3D repository

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3D#55]
Files to move to LFS:
*.gld
*.mesh
*.png
*.jpg
*.dll (*yes we do check some of these in*)

Existing files of these types need to be removed I guess?
https://help.github.com/en/github/managing-large-files/moving-a-file-in-your-repository-to-git-large-file-storage

**Comment by cwbooth5** [comment]
ALL DONE
