### ISSUE TITLE
Add script for deploying docker droplet

### ISSUE THREAD

**Issue by Wavesonics** [FugitiveTheGame/Fugitive3D#74]
This will make setting up for play tests very easy.

**Comment by cwbooth5** [comment]
There will  be two primary components here: droplet interactions and game server interactions.

Droplet stuff:
- list running droplets
- test they are reachable via ssh
- CRUD ops on droplets

Game server stuff:
- set server name, port, or --private flags
- get server status
- deploy new server on existing droplet (or a new one)

I'm still trying to figure out if we want to have many servers running inside a single container or one container per game server instance.
